//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentManual
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSolution
    {
        public int TASK_SOLUTION_ID { get; set; }
        public System.DateTime TASK_SOLUTION_DATE { get; set; }
        public int TASK_SOLUTION_RESULT_ID { get; set; }
        public int TASK_SOLUTION_TASK_ID { get; set; }
        public int TASK_SOLUTION_ANSWERER_ID { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
